set_property SRC_FILE_INFO {cfile:/home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/adc.xdc rfile:../../../src/constraints/adc.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/bridge.xdc rfile:../../../src/constraints/bridge.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/clk.xdc rfile:../../../src/constraints/clk.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/gpio.xdc rfile:../../../src/constraints/gpio.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/led.xdc rfile:../../../src/constraints/led.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/rst.xdc rfile:../../../src/constraints/rst.xdc id:6} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/sram.xdc rfile:../../../src/constraints/sram.xdc id:7} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {adc_data_i[0]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {adc_data_i[1]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {adc_data_i[2]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {adc_data_i[3]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {adc_data_i[4]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports {adc_data_i[5]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {adc_data_i[6]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L13 [get_ports {adc_data_i[7]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {adc_data_i[8]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {adc_data_i[9]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {adc_ovrng_i}]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {spi_nss_i}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports {spi_sck_i}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10 [get_ports {spi_mosi_i}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B13 [get_ports {spi_miso_o}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {nu_io[0]}]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {nu_io[1]}]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {nu_io[2]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports {nu_io[3]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G11 [get_ports clk_i]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P13 [get_ports {gpio_io[0]}]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P12 [get_ports {gpio_io[1]}]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P11 [get_ports {gpio_io[2]}]
set_property src_info {type:XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P10 [get_ports {gpio_io[3]}]
set_property src_info {type:XDC file:5 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {led_o[1]}]
set_property src_info {type:XDC file:5 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports {led_o[2]}]
set_property src_info {type:XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C5 [get_ports {led_o[3]}]
set_property src_info {type:XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {led_o[4]}]
set_property src_info {type:XDC file:6 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11 [get_ports {nrst_i}]
set_property src_info {type:XDC file:7 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {sram_data_io[0]}]
set_property src_info {type:XDC file:7 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {sram_data_io[1]}]
set_property src_info {type:XDC file:7 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports {sram_data_io[2]}]
set_property src_info {type:XDC file:7 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B3 [get_ports {sram_data_io[3]}]
set_property src_info {type:XDC file:7 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {sram_data_io[4]}]
set_property src_info {type:XDC file:7 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {sram_data_io[5]}]
set_property src_info {type:XDC file:7 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E4 [get_ports {sram_data_io[6]}]
set_property src_info {type:XDC file:7 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D2 [get_ports {sram_data_io[7]}]
set_property src_info {type:XDC file:7 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {sram_data_io[8]}]
set_property src_info {type:XDC file:7 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H3 [get_ports {sram_data_io[9]}]
set_property src_info {type:XDC file:7 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports {sram_data_io[10]}]
set_property src_info {type:XDC file:7 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {sram_data_io[11]}]
set_property src_info {type:XDC file:7 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports {sram_data_io[12]}]
set_property src_info {type:XDC file:7 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {sram_data_io[13]}]
set_property src_info {type:XDC file:7 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports {sram_data_io[14]}]
set_property src_info {type:XDC file:7 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {sram_data_io[15]}]
set_property src_info {type:XDC file:7 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {sram_address_o[0]}]
set_property src_info {type:XDC file:7 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {sram_address_o[1]}]
set_property src_info {type:XDC file:7 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2 [get_ports {sram_address_o[2]}]
set_property src_info {type:XDC file:7 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1 [get_ports {sram_address_o[3]}]
set_property src_info {type:XDC file:7 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports {sram_address_o[4]}]
set_property src_info {type:XDC file:7 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {sram_address_o[5]}]
set_property src_info {type:XDC file:7 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {sram_address_o[6]}]
set_property src_info {type:XDC file:7 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {sram_address_o[7]}]
set_property src_info {type:XDC file:7 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {sram_address_o[8]}]
set_property src_info {type:XDC file:7 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports {sram_address_o[9]}]
set_property src_info {type:XDC file:7 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {sram_address_o[10]}]
set_property src_info {type:XDC file:7 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports {sram_address_o[11]}]
set_property src_info {type:XDC file:7 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports {sram_address_o[12]}]
set_property src_info {type:XDC file:7 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F1 [get_ports {sram_address_o[13]}]
set_property src_info {type:XDC file:7 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports {sram_address_o[14]}]
set_property src_info {type:XDC file:7 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports {sram_address_o[15]}]
set_property src_info {type:XDC file:7 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports {sram_address_o[16]}]
set_property src_info {type:XDC file:7 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {sram_ce_n_o}]
set_property src_info {type:XDC file:7 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {sram_oe_n_o}]
set_property src_info {type:XDC file:7 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports {sram_we_n_o}]
set_property src_info {type:XDC file:7 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {sram_lb_n_o}]
set_property src_info {type:XDC file:7 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {sram_ub_n_o}]
