# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7s15ftgb196-1IL

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/multichannel-analysis.cache/wt [current_project]
set_property parent.project_path /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/multichannel-analysis.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/multichannel-analysis.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/design/adc_driver.vhdl
  /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/design/spi_cmd.vhdl
  /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/design/control.vhdl
  /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/design/rst_driver.vhdl
  /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/design/spi_driver.vhdl
  /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/design/sram_driver.vhdl
  /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/design/top.vhdl
}
read_ip -quiet /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/multichannel-analysis.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/multichannel-analysis.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/multichannel-analysis.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/multichannel-analysis.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/adc.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/adc.xdc]

read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/bridge.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/bridge.xdc]

read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/clk.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/clk.xdc]

read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/fpga.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/fpga.xdc]

read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/gpio.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/gpio.xdc]

read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/led.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/led.xdc]

read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/rst.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/rst.xdc]

read_xdc /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/sram.xdc
set_property used_in_implementation false [get_files /home/wykys/projects/upol-ma105msps10b-fpga/multichannel-analysis/src/constraints/sram.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7s15ftgb196-1IL


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
